-- Create exportations table
CREATE TABLE IF NOT EXISTS exportations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    exportation_id VARCHAR(50) UNIQUE,
    reference_number VARCHAR(100),
    product_type VARCHAR(100),
    amount DECIMAL(10,2),
    destination VARCHAR(100),
    exportation_date DATE,
    export_date DATE,
    unit_price DECIMAL(10,2),
    currency VARCHAR(3),
    has_delivery BOOLEAN DEFAULT FALSE,
    status VARCHAR(50),
    notes TEXT,
    customer_name VARCHAR(100),
    customer_email VARCHAR(100),
    customer_phone VARCHAR(20),
    document_number VARCHAR(50),
    export_license VARCHAR(50),
    employee_id VARCHAR(50),
    transport_method VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_exportation_id (exportation_id),
    INDEX idx_status (status),
    INDEX idx_destination (destination),
    INDEX idx_export_date (exportation_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
